// src/components/About.vue
<script>
export default {
  name: 'About',
}
</script>

<template>
  <section
    id="about"
    class="flex justify-center bg-white px-30 py-20 transition-colors duration-500 dark:bg-gray-900"
  >
    <img
      src="@/assets/profile.jpg"
      alt="Profile Picture"
      class="mr-20 block h-70 rounded-full duration-500 ease-in-out dark:hidden"
    />
    <img
      src="@/assets/profile-dark.jpg"
      alt="Dark Profile Picture"
      class="mr-20 hidden h-70 rounded-full duration-500 ease-in-out dark:block"
    />
    <div class="my-auto">
      <h3 class="mb-6 text-2xl font-semibold text-blue-600 dark:text-blue-400">About Me</h3>
      <p class="mx-auto max-w-3xl leading-relaxed text-slate-600 dark:text-slate-300">
        I am a Full Stack Developer in training at EBAC, with a solid background in mechanical
        engineering and process analysis. Throughout my career, I have developed an analytical,
        results-oriented profile, combined with a quick learning ability and ease in working with
        multidisciplinary teams.
      </p>
      <p class="mx-auto max-w-3xl pt-5 leading-relaxed text-slate-600 dark:text-slate-300">
        Currently, I am transitioning to the technology field, where I have been building responsive
        websites, landing pages, and interactive tools. My initial focus is to work as a front-end
        developer, using technologies such as TypeScript, React, and other modern web development
        tools.
      </p>
    </div>
  </section>
</template>

// src/containers/About/index.tsx
import React from 'react'
import Title from '../../components/Title'
import Paragraph from '../../components/Paragraph'
import { GithubSection, Technologies } from './styles'

const About = () => (
  <section>
    <Title fontSize={16}>About</Title>
    <Paragraph type="main">
      I am a Full Stack Developer in training at EBAC, with solid experience in
      mechanical engineering and process analysis. Throughout my career, I have
      developed an analytical, results-oriented profile, combined with quick
      learning and ease in working with multidisciplinary teams.
    </Paragraph>
    <Technologies>
      <p>Front-end:</p>
      <img src="https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white" />
      <img src="https://img.shields.io/badge/CSS3-1572B6?style=for-the-badge&logo=css3&logoColor=white" />
      <img src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E" />
      <img src="https://img.shields.io/badge/TypeScript-007ACC?style=for-the-badge&logo=typescript&logoColor=white" />
      <img src="https://img.shields.io/badge/Vue%20js-35495E?style=for-the-badge&logo=vuedotjs&logoColor=4FC08D" />
      <img src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB" />
      <img src="https://img.shields.io/badge/Redux-593D88?style=for-the-badge&logo=redux&logoColor=white" />
    </Technologies>
    <Technologies>
      <p>Back-end:</p>
      <img src="https://img.shields.io/badge/Node%20js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white" />
      <img src="https://img.shields.io/badge/Python-FFD43B?style=for-the-badge&logo=python&logoColor=blue" />
      <img src="https://img.shields.io/badge/Express%20js-000000?style=for-the-badge&logo=express&logoColor=white" />
    </Technologies>
    <Technologies>
      <p>Tools:</p>
      <img src="https://img.shields.io/badge/GIT-E44C30?style=for-the-badge&logo=git&logoColor=white" />
      <img src="https://img.shields.io/badge/Sass-CC6699?style=for-the-badge&logo=sass&logoColor=white" />
      <img src="https://img.shields.io/badge/Gulp-CF4647?style=for-the-badge&logo=gulp&logoColor=white" />
      <img src="https://img.shields.io/badge/Bootstrap-563D7C?style=for-the-badge&logo=bootstrap&logoColor=white" />
    </Technologies>
    <GithubSection>
      <img src="https://github-readme-stats.vercel.app/api?username=gustavokasaki&show_icons=true&theme=dracula&include_all_commits=true&count_private=true" />
      <img src="https://github-readme-stats.vercel.app/api/top-langs/?username=gustavokasaki&layout=compact&langs_count=7&theme=dracula" />
    </GithubSection>
  </section>
)

export default About
